### ISSUE TITLE
Add new mirrors for nxp

### ISSUE THREAD

**Issue by chakuzo** [jhnc-oss/github-mirror#70]
meta-freescale
meta-freescale-3rdparty
meta-freescale-distro
meta-imx
meta-nxp-demo-experience
meta-qt6

**Comment by h5b** [comment]
- [ ] meta-freescale (https://github.com/jhnc-oss/github-mirror/blob/main/.github/workflows/mirror.yml#L139)
- [ ] meta-freescale-distro (https://github.com/jhnc-oss/github-mirror/blob/main/.github/workflows/mirror.yml#L135)

**Comment by chakuzo** [comment]
meta-imx scheint wohl auch zu existieren nur keine keys? 

Ich habe keine Berechtigung um in diesem Projekt Keys anzulegen und einzutragen. Aber die folgenden Forks habe ich schonmal angelegt.

- meta-freescale-3rdparty
- meta-nxp-demo-experience

**Comment by h5b** [comment]
@chakuzo so the remaining repositories to mirror are:
- [ ] https://code.qt.io/cgit/yocto/meta-qt6.git/
- [ ] https://github.com/Freescale/meta-freescale-3rdparty

**Comment by h5b** [comment]
@chakuzo done
