### ISSUE TITLE
Fix yocto-meta-kf6 to github-mirror

### ISSUE THREAD

**Issue by h5b** [jhnc-oss/github-mirror#92]

**Comment by offa** [comment]
It's configured already, but looks wired: https://github.com/jhnc-oss/github-mirror/blob/main/.github/workflows/mirror.yml#L155

Mirrored to itself!?

**Comment by h5b** [comment]
> It's configured already, but looks wired: https://github.com/jhnc-oss/github-mirror/blob/main/.github/workflows/mirror.yml#L155
> 
> Mirrored to itself!?

Wired as in weird.
